# Generated by Django 5.1.5 on 2025-02-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Regulatoria', 'Regulatoria'), ('No Regulatoria', 'No Regulatoria'), ('Difusión', 'Difusión')], max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='medidas.medida')),
            ],
        ),
    ]
